Fix for Issue -63 add VCN (subnets) Logging - Issue #63
oracle-terraform-modules/terraform-oci-vcn pull request #131
Opened 2023-11-29 16:32 UTC by syedthameem85

# Proposed change

## How has these changes been tested?

### Automated testing

If you're running automated testing for this module, we would love to hear from you, and potentially integrate it to the module standard workflow.

### Manual testing

If no automated testing is run, please ensure that at least the three steps below are passing without any error.

- [ ] Running `terraform apply` on each example provided with this module provisions the intended resource(s) without any errors.
- [ ] Modifying module's *Input Variables* after initial provisioning behaves as intended, i.e: any updateable properties are ameneded without recreation of the resource(s).
- [ ] Running `terraform destroy` on each example provided with this module destroys all the resources created by this module and only the resources created by this module.

## Checklist before submitting your PR

- [ ] My code follows [the style guidelines of this project](../tree/main/docs/codingconventions.adoc)
- [ ] these changes provision new resources:
  - [ ] I have updated the README introduction section (README.adoc)
  - [ ] I have updated the README introduction section (README.md)
- [ ] these changes adds any new variables:
  - [ ] I have updated [docs/terraformoptions.adoc](../tree/main/docs/terraformoptions.adoc) to include each variable
- [ ] I have updated the changelog to include an entry for these changes
- [ ] I have updated all provided examples, including each README file and all applicable code blocks
- [ ] these changes generates no new warnings
- [ ] Any dependent changes have been merged and published in upstream modules

Note: *If you are not an Oracle employee, to contribute to an Oracle-sponsored open-source project, you need to sign the [Oracle Contributor Agreement (OCA)](https://oca.opensource.oracle.com/).*

2023-11-30 00:04 UTC, syedthameem85 commented
@hyder  - This PR is the solution for the issue https://github.com/oracle-terraform-modules/terraform-oci-vcn/issues/63 - https://github.com/oracle-terraform-modules/terraform-oci-vcn/issues/63

2024-02-08 06:52 UTC, hyder commented on variables.tf
> +variable "enable_vcn_logging" {
bring the control variable of the feature before the variable used to configure the feature i.e. define enable_ first and then the retention.

2024-02-08 06:53 UTC, hyder commented on variables.tf
> +  default     = 30
please explicitly indicate the duration.

2024-02-08 06:53 UTC, hyder commented on vcn.tf
> +  service_logdef = { for k in local.subnet : format("%s_%s", k, "log") => { loggroup = "loggrp", service = "flowlogs", resource = k } }
please format your code before committing

2024-02-08 06:55 UTC, hyder commented on vcn_gateways.tf
> +resource "oci_core_public_ip" "nat_gateway_public_ip" {
please submit separately so we can track. Don't mix features/fixes.

2024-02-08 06:56 UTC, hyder requested changes
please see comments.

2024-02-10 18:08 UTC, closed without merging

2024-02-10 18:19 UTC, hyder commented
Why did you close it?