WIP road to v3.0.0
oracle-terraform-modules/terraform-oci-vcn pull request #55
Opened 2021-08-30 12:54 UTC by kral2

This PR should fix all remaining open points in [milestone v3.0.0](https://github.com/oracle-terraform-modules/terraform-oci-vcn/milestone/3).

# Proposed change

- [x] fix #24
- [x] fix #54
- [ ] fix #30
- [ ] fix #44

## How has these changes been tested?

### Manual testing

If no automated testing is run, please ensure that at least the three steps below are passing without any error.

- [ ] Running `terraform apply` on each example provided with this module provisions the intended resource(s) without any errors.
- [ ] Modifying module's *Input Variables* after initial provisioning behaves as intended, i.e: any updateable properties are ameneded without recreation of the resource(s).
- [ ] Running `terraform destroy` on each example provided with this module destroys all the resources created by this module and only the resources created by this module.

## Checklist before submitting your PR

- [x] My code follows [the style guidelines of this project](../tree/main/docs/codingconventions.adoc)
- [ ] these changes provision new resources:
  - [ ] I have updated the README introduction section (README.adoc)
  - [ ] I have updated the README introduction section (README.md)
- [ ] these changes adds any new variables:
  - [ ] I have updated [docs/terraformoptions.adoc](../tree/main/docs/terraformoptions.adoc) to include each variable
- [ ] I have updated the changelog to include an entry for these changes
- [ ] I have updated all provided examples, including each README file and all applicable code blocks
- [ ] these changes generates no new warnings
- [ ] Any dependent changes have been merged and published in upstream modules

Note: *If you are not an Oracle employee, to contribute to an Oracle-sponsored open-source project, you need to sign the [Oracle Contributor Agreement (OCA)](https://oca.opensource.oracle.com/).*

2021-08-31 00:11 UTC, hyder requested changes

2021-08-31 00:11 UTC, hyder commented on variables.tf
>  variable "drg_display_name" {
Add a validation condition so the display name in the terraform.tfvars file is not an empty string: https://www.terraform.io/docs/language/values/variables.html#custom-validation-rules

2021-08-31 00:11 UTC, hyder commented on variables.tf
> +variable "nat_gateway_display_name" {
Add a validation condition so the display name in the terraform.tfvars file is not an empty string: https://www.terraform.io/docs/language/values/variables.html#custom-validation-rules

2021-08-31 00:11 UTC, hyder commented on variables.tf
> +variable "service_gateway_display_name" {
Add a validation condition so the display name in the terraform.tfvars file is not an empty string: https://www.terraform.io/docs/language/values/variables.html#custom-validation-rules

2021-08-31 00:11 UTC, hyder commented on variables.tf
> +variable "internet_gateway_display_name" {
Add a validation condition so the display name in the terraform.tfvars file is not an empty string: https://www.terraform.io/docs/language/values/variables.html#custom-validation-rules

2021-08-31 07:38 UTC, kral2 commented on .terraform.lock.hcl
> +  version     = "4.41.0"
That was a mistake: >= is what we want. I will correct that

I had to bump the version to support some naming options on DRG attachment, but did not found the required version: just took the last one ...

2021-08-31 07:40 UTC, kral2 commented on vcn_gateways.tf
> +  display_name = var.label_prefix == "none" ? "${var.drg_display_name}_to_${oci_core_vcn.vcn.display_name}" : "${var.label_prefix}-${var.drg_display_name}_to_${oci_core_vcn.vcn.display_name}"
You mean <name_with_underscore>-to-<name_with_underscore> ?

2021-09-03 02:08 UTC, hyder approved these changes
approved

2021-09-03 02:22 UTC, merged